---
title: "state_employment"
format: html
editor: visual
---

## Running Code

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).

## Load Assets
```{r}
library(tidyverse)
library(readxl)
#1
states_1999 <- read_excel("data/state_naicssector_1999.xls", skip = 7)
states_2000 <- read_excel("data/state_naicssector_2000.xls", skip = 7)
states_2001 <- read_excel("data/state_naicssector_2001.xls", skip = 7)
states_2002 <- read_excel("data/state_naicssector_2002.xls", skip = 5)
states_2003 <- read_excel("data/state_naicssector_2003.xls", skip = 7)
states_2004 <- read_excel("data/state_naicssector_2004.xls", skip = 7)
states_2005 <- read_excel("data/state_naicssector_2005.xls", skip = 7)
states_2006 <- read_excel("data/state_naicssector_2006.xls", skip = 7)
#2
states_2007 <- read_excel("data/state_naicssector_2007.xls", skip = 6)
states_2008 <- read_excel("data/state_naicssector_2008.xls", skip = 5) 
#3
states_2009 <- read_excel("data/state_naicssector_2009.xls", skip = 4)
states_2010 <- read_excel("data/state_naicssector_2010.xls", skip = 4)
states_2011 <- read_excel("data/state_naicssector_2011.xls", skip = 4)
states_2012 <- read_excel("data/state_naicssector_2012.xls", skip = 5)
states_2013 <- read_excel("data/state_naicssector_2013.xlsx", skip = 5)
states_2014 <- read_excel("data/state_naicssector_2014.xlsx", skip = 5)
states_2015 <- read_excel("data/state_naicssector_2015.xlsx", skip = 5)
states_2016 <- read_excel("data/state_naicssector_2016.xlsx", skip = 6)
#4
states_2017 <- read_excel("data/us_state_naicssector_lfo_2017.xlsx", skip = 2)
states_2018 <- read_excel("data/us_state_naicssector_lfo_2018.xlsx", skip = 2)
states_2019 <- read_excel("data/us_state_naicssector_lfo_2019.xlsx", skip = 2)
states_2020 <- read_excel("data/us_state_naicssector_lfo_2020.xlsx", skip = 2)
states_2021 <- read_excel("data/us_state_naicssector_lfo_2021.xlsx", skip = 2)

```


```{r}

states_1999 <- states_1999 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 1999)

states_2000 <- states_2000 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 2000) 

states_2001 <- states_2001 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 2001)

states_2002 <-  states_2002 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 2002) |>
  rename(AREA = "STATE")

states_2003 <- states_2003 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 2003)

states_2004 <- states_2004 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 2004)

states_2005 <- states_2005 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL) |>
  mutate(year = 2005)

states_2006 <-  states_2006 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total")) |>
  select(1:5) |>
  pivot_wider(names_from = `DATA TYPE`, values_from = TOTAL)  |>
  mutate(year = 2006)

```


```{r}
states_2007 <-  states_2007 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), SIZE == "1:   Total") |>
  select(1:7) |>
  mutate(year = 2007) |>
  rename("STATE DESCRIPTION" = "AREA", 
         "ENTERPRISE EMPLOYMENT SIZE" = "SIZE",
         "NUMBER OF FIRMS" = "OF FIRMS",
         "NUMBER OF ESTABLISHMENTS" = "ESTABLISHMENTS")

states_2008 <-  states_2008 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), SIZE == "1:   Total") |>
  select(1:8) |>
  mutate(year = 2008) |>
  rename("STATE DESCRIPTION" = "AREA DESCRIPTION", 
         "ENTERPRISE EMPLOYMENT SIZE" = "SIZE",
         "NUMBER OF FIRMS" = "OF FIRMS",
         "NUMBER OF ESTABLISHMENTS" = "ESTABLISHMENTS")

states_2009 <-  states_2009 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "1:   Total") |>
  select(1:8) |>
  mutate(year = 2009)

states_2010 <-  states_2010 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "1:   Total") |>
  select(1:8) |>
  mutate(year = 2010)

states_2011 <-  states_2011 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "1:   Total") |>
  select(1:8) |>
  mutate(year = 2011)

states_2012 <-  states_2012 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "01:  Total") |>
  select(1:8) |>
  mutate(year = 2012)

states_2013 <-  states_2013 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "01:  Total") |>
  select(1:8) |>
  mutate(year = 2013)

states_2014 <-  states_2014 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "01:  Total") |>
  select(1:8) |>
  mutate(year = 2014)

states_2015 <-  states_2015 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "01:  Total") |>
  select(1:8) |>
  mutate(year = 2015)

states_2016 <-  states_2016 |>
  filter(`NAICS DESCRIPTION` %in% c("Information", "Total"), `ENTERPRISE EMPLOYMENT SIZE` == "01:  Total") |>
  select(1:8) |>
  mutate(year = 2016)
```

```{r}
states_2017 <- states_2017 |>
  filter(`NAICS Description` %in% c("Information", "Total"), 
         `Enterprise Size` == "1: Total", 
         `State Name`!= "United States", 
         LFO == "1: Total") |>
  select(1:9) |>
  mutate(year = 2017)

states_2018 <- states_2018 |>
  filter(`NAICS Description` %in% c("Information", "Total"), 
         `Enterprise Size` == "1: Total", 
         `State Name`!= "United States", 
         LFO == "1: Total") |>
  select(1:9) |>
  mutate(year = 2018)

states_2019 <- states_2019 |>
  filter(`NAICS Description` %in% c("Information", "Total"), 
         `Enterprise Size` == "1: Total", 
         `State Name`!= "United States", 
         LFO == "1: Total") |>
  select(1:9) |>
  mutate(year = 2019)

states_2020 <- states_2020 |>
  filter(`NAICS Description` %in% c("Information", "Total"), 
         `Enterprise Size` == "1: Total", 
         `State Name`!= "United States", 
         LFO == "1: Total") |>
  select(1:9) |>
  mutate(year = 2020)

states_2021 <- states_2021 |>
  filter(`NAICS Description` %in% c("Information", "Total"), 
         `Enterprise Size` == "1: Total", 
         `State Name`!= "United States", 
         LFO == "1: Total") |>
  select(1:9) |>
  mutate(year = 2021)

```

```{r}
full <- states_1999 |>
  bind_rows(states_2000) |>
  bind_rows(states_2001) |>
  bind_rows(states_2002) |>
  bind_rows(states_2003) |>
  bind_rows(states_2004) |>
  bind_rows(states_2005) |>
  bind_rows(states_2006) |>
  rename("NAICS Description" = "NAICS DESCRIPTION",
         "State Name" = "AREA") |>
  mutate(Firms = as.numeric(Firms), 
         Establishments = as.numeric(Establishments), 
         Employment = as.numeric(Employment))

full2 <- states_2007 |>
  bind_rows(states_2008) |>
  bind_rows(states_2009) |>
  bind_rows(states_2010) |>
  bind_rows(states_2011) |>
  bind_rows(states_2012) |>
  bind_rows(states_2013) |>
  bind_rows(states_2014) |>
  bind_rows(states_2015) |>
  bind_rows(states_2016) |>
  rename("NAICS Description" = "NAICS DESCRIPTION",
         "State Name" = "STATE DESCRIPTION",
         "Enterprise Size" = "ENTERPRISE EMPLOYMENT SIZE",
         "Firms" = "NUMBER OF FIRMS",
         "Establishments" = "NUMBER OF ESTABLISHMENTS",
         "Employment" = "EMPLOYMENT")

full3 <- states_2017 |>
  bind_rows(states_2018) |>
  bind_rows(states_2019) |>
  bind_rows(states_2020) |>
  bind_rows(states_2021)

final <- full |>
  bind_rows(full2) |>
  bind_rows(full3) |>
  select(1:8)
  
```


```{r}
final_total <- final |>
  filter(`NAICS Description` == "Total") |>
  select(Employment, year)

final_info <- final |>
  filter(`NAICS Description` == "Information") |>
  select(Employment, year)

```

```{r}

filter(final_info, year == 2021) |>
  select(1) |>
  view()

filter(final_total, year == 2021) |>
  select(1) |>
  view()



```

